// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPU24FIlqYG1b9Qe2-gu3Urv8KVSdNDYY',
    appId: '1:440400020257:web:7b6322a435f06abcfb3460',
    messagingSenderId: '440400020257',
    projectId: 'universai',
    authDomain: 'universai.firebaseapp.com',
    storageBucket: 'universai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkaav3t_s568E9BEeOTTM1H5lsgxy7f3Q',
    appId: '1:440400020257:android:eba51e6d00648d37fb3460',
    messagingSenderId: '440400020257',
    projectId: 'universai',
    storageBucket: 'universai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1nqeKfHDLr337vq3lqOJpZIJXm-R17c',
    appId: '1:440400020257:ios:f4b40f53baa7aefafb3460',
    messagingSenderId: '440400020257',
    projectId: 'universai',
    storageBucket: 'universai.appspot.com',
    iosBundleId: 'com.example.universaiAdmin',
  );
}
